# https://taskfile.dev

version: '3'

tasks:
  ci:
    desc: Run CI tasks
    cmds:
      - task: test
      - task: lint

  test:
    desc: Run tests
    cmd: go test -v ./...

  lint:
    desc: Run linter
    cmd: golangci-lint run ./...
